- name: Create a PostgreSQL user
  become: yes
  become_user: postgres
  postgresql_user: 
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    encrypted: true
    role_attr_flags: "SUPERUSER,CREATEROLE,CREATEDB,REPLICATION,LOGIN"